name: Build

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                java-version: '11'

            - name: Setup Maven
              run: |
              echo "<settings><activeProfiles><activeProfile>github</activeProfile></activeProfiles><profiles><profile><id>github</id><repositories><repository><id>central</id><url>https://repo1.maven.org/maven2</url><releases><enabled>true</enabled></releases><snapshots><enabled>true</enabled></snapshots></repository><repository><id>github</id><name>Jeffrey Riggle Apache Maven Packages</name><url>https://maven.pkg.github.com/jeffreyriggle/java-core</url></repository></repositories></profile></profiles><servers><server><id>github</id><username>JeffreyRiggle</username><password>\${env.TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml

            - name: Build with Maven
              run: mvn test
            
            - name: Deploy
              env:
                TOKEN: ${{ secrets.GITHUBTOKEN }}
              run: mvn deploy -Drevision="${GITHUB_RUN_NUMBER}"